{% set name = "omero-dropbox" %}
{% set version = "5.5.dev1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94251d8059c3e9fdce5714b9f776842041e5e986674c15bb53b810b915235518

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  script_env:
    - VERSION_SUFFIX

requirements:
  host:
    - pip
    - python =2.7
  run:
    - omero-py =5.5
    - python =2.7

test:
  imports:
    - fsFileServer
    - fsMonitorServer

about:
  home: https://docs.openmicroscopy.org/latest/omero/developers/Server/FS.html
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  license_file: 
  summary: OMERO.dropbox server for watching directories
  doc_url: https://docs.openmicroscopy.org/latest/omero/developers
  dev_url: https://github.com/ome/omero-dropbox

extra:
  recipe-maintainers:
    - ome
